"""create_initial_tables

Revision ID: 4f1e344f080a
Revises:
Create Date: 2026-06-21 16:03:50.606969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4f1e344f080a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attachments",
        "storage_key",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_attachments_storage_key"), table_name="attachments")
    op.create_index(
        op.f("ix_attachments_storage_key"), "attachments", ["storage_key"], unique=False
    )
    op.alter_column(
        "events",
        "end_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "events",
        "generate_task",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_index(op.f("idx_events_owner_resident_id"), table_name="events")
    op.drop_index(op.f("idx_events_recurrence_id"), table_name="events")
    op.drop_index(op.f("idx_events_residence_id"), table_name="events")
    op.drop_index(op.f("idx_message_reads_message_id"), table_name="message_reads")
    op.drop_index(op.f("idx_message_reads_resident_id"), table_name="message_reads")
    op.drop_constraint(
        op.f("message_reads_message_id_resident_id_key"),
        "message_reads",
        type_="unique",
    )
    op.alter_column(
        "messages",
        "pinned",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_index(op.f("idx_messages_residence_id"), table_name="messages")
    op.drop_index(op.f("idx_notifications_user_id"), table_name="notifications")
    op.alter_column(
        "profiles", "first_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "profiles", "last_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.drop_index(op.f("idx_profiles_user_id"), table_name="profiles")
    op.alter_column(
        "residence_settings",
        "guest_retention_days",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "residence_settings",
        "notifications_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "residence_settings",
        "default_currency",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
    )
    op.drop_index(
        op.f("idx_residence_settings_residence_id"), table_name="residence_settings"
    )
    op.alter_column(
        "residents",
        "income_weight",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        nullable=False,
    )
    op.drop_index(op.f("idx_residents_residence_id"), table_name="residents")
    op.drop_index(op.f("idx_residents_user_id"), table_name="residents")
    op.drop_constraint(
        op.f("residents_residence_id_user_id_key"), "residents", type_="unique"
    )
    op.create_unique_constraint(None, "residents", ["user_id"])
    op.drop_index(op.f("idx_task_executions_resident_id"), table_name="task_executions")
    op.drop_index(op.f("idx_task_executions_task_id"), table_name="task_executions")
    op.drop_index(op.f("idx_tasks_assigned_resident_id"), table_name="tasks")
    op.drop_index(op.f("idx_tasks_recurrence_id"), table_name="tasks")
    op.drop_index(op.f("idx_tasks_residence_id"), table_name="tasks")
    op.alter_column(
        "user_preferences",
        "language",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
    )
    op.alter_column(
        "user_preferences", "theme", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        "user_preferences", "push_enabled", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_index(op.f("idx_user_preferences_user_id"), table_name="user_preferences")
    op.alter_column("users", "password_hash", existing_type=sa.TEXT(), nullable=True)
    op.drop_index(op.f("idx_users_email"), table_name="users")
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.alter_column("users", "password_hash", existing_type=sa.TEXT(), nullable=False)
    op.create_index(
        op.f("idx_user_preferences_user_id"),
        "user_preferences",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "user_preferences", "push_enabled", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "user_preferences", "theme", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.alter_column(
        "user_preferences",
        "language",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
    )
    op.create_index(
        op.f("idx_tasks_residence_id"), "tasks", ["residence_id"], unique=False
    )
    op.create_index(
        op.f("idx_tasks_recurrence_id"), "tasks", ["recurrence_id"], unique=False
    )
    op.create_index(
        op.f("idx_tasks_assigned_resident_id"),
        "tasks",
        ["assigned_resident_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_task_executions_task_id"),
        "task_executions",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_task_executions_resident_id"),
        "task_executions",
        ["resident_id"],
        unique=False,
    )
    op.drop_constraint(None, "residents", type_="unique")
    op.create_unique_constraint(
        op.f("residents_residence_id_user_id_key"),
        "residents",
        ["residence_id", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_residents_user_id"), "residents", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_residents_residence_id"), "residents", ["residence_id"], unique=False
    )
    op.alter_column(
        "residents",
        "income_weight",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        nullable=True,
    )
    op.create_index(
        op.f("idx_residence_settings_residence_id"),
        "residence_settings",
        ["residence_id"],
        unique=False,
    )
    op.alter_column(
        "residence_settings",
        "default_currency",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
    )
    op.alter_column(
        "residence_settings",
        "notifications_enabled",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "residence_settings",
        "guest_retention_days",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.create_index(op.f("idx_profiles_user_id"), "profiles", ["user_id"], unique=False)
    op.alter_column(
        "profiles", "last_name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "profiles", "first_name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.create_index(
        op.f("idx_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_messages_residence_id"), "messages", ["residence_id"], unique=False
    )
    op.alter_column(
        "messages",
        "pinned",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.create_unique_constraint(
        op.f("message_reads_message_id_resident_id_key"),
        "message_reads",
        ["message_id", "resident_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_message_reads_resident_id"),
        "message_reads",
        ["resident_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_message_reads_message_id"),
        "message_reads",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_events_residence_id"), "events", ["residence_id"], unique=False
    )
    op.create_index(
        op.f("idx_events_recurrence_id"), "events", ["recurrence_id"], unique=False
    )
    op.create_index(
        op.f("idx_events_owner_resident_id"),
        "events",
        ["owner_resident_id"],
        unique=False,
    )
    op.alter_column(
        "events",
        "generate_task",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "events",
        "end_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_index(op.f("ix_attachments_storage_key"), table_name="attachments")
    op.create_index(
        op.f("idx_attachments_storage_key"),
        "attachments",
        ["storage_key"],
        unique=False,
    )
    op.alter_column(
        "attachments",
        "storage_key",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
